mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from . import views
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='polls:index',
                                  permanent=False)),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup')
]

poll/urls.py
from django.urls import path

from . import views
from django.urls import include, path

app_name = 'poll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('profile/', views.profile, name='profile')]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    """
    A class representing a question.

    Attributes:
        question_text (str): The text of the question.
        pub_date (DateTime): The date and time when the question was published.
        end_date (DateTime): The date and time when the question's voting
                             period ends (optional).
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date', default=timezone.now)
    end_date = models.DateTimeField('end published date', null=True,
                                    blank=True)

    def pub_date_str(self):
        """
        Returns the pub_date as a formatted string.
        """
        return self.pub_date.strftime('%Y-%m-%d %H:%M:%S')

    def end_date_str(self):
        """
        Returns the end_date as a formatted string or None if it's not set.
        """
        return self.end_date.strftime('%Y-%m-%d %H:%M:%S') if self.end_date else None

    def __str__(self):
        """
        Returns a string representation of the question.
        """
        return self.question_text

    def was_published_recently(self):
        """
        Checks if the question was published recently (within the last day).

        Returns:
            bool: True if the question was published recently, False otherwise.
        """
        now = timezone.now()
        return (now - datetime.timedelta(days=1)) <= self.pub_date <= now

    def is_published(self):
        """
        Checks if the question is currently published.

        Returns:
            bool: True if the question is published, False otherwise.
        """
        return timezone.now() >= self.pub_date

    def can_vote(self):
        """
        Checks if the question can be voted on based on its publishing
        and end dates.

        Returns:
            bool: True if the question can be voted on, False otherwise.
        """
        if self.end_date is None:
            return timezone.now() >= self.pub_date
        else:
            return self.end_date >= timezone.now() >= self.pub_date


class Choice(models.Model):
    """
    A class representing a choice for a question.

    Attributes:
        question (Question): The question to which this choice belongs.
        choice_text (str): The text of the choice.
        votes (int): The number of votes this choice has received.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        """
        Returns a string representation of the choice.
        """
        return self.choice_text

    @property
    def votes(self):
        """Return the number of votes for this choice."""
        return self.vote_set.count()


class Vote(models.Model):
    """
    Record a choice for a question made by a user
    """
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} voted for {self.choice.choice_text}"

polls/views.py
from django.http import HttpResponseRedirect,Http404
from .models import Question, Choice, Vote
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.contrib import messages


class IndexView(generic.ListView):
    """
    View for displaying a list of the latest published questions.
    """
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        all_questions = Question.objects.all()
        # Check if the question is published recently and can be voted on.
        question = [q for q in all_questions if q.is_published() and q.can_vote()]
        # Sort and select the last 5 questions.
        return Question.objects.filter(question_text__in=question).order_by("-pub_date")


class DetailView(generic.DetailView):
    """
    View for displaying details of a question.
    """
    model = Question
    template_name = 'polls/detail.html'


    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        all_questions = Question.objects.all()
        # Check if the question is published recently.
        question = [q for q in all_questions if q.is_published()]

        return Question.objects.filter(question_text__in=question)

    def get(self, request, *args, **kwargs):
        # Check if the object exists
        try:
            self.get_object()
        except Http404:
            return HttpResponseRedirect(reverse('polls:index'))  # Redirect to the index page
        #still go to detail page
        return super().get(request, *args, **kwargs)

    def get_old_choice(self):

        user = self.request.user
        if user == AnonymousUser():
            return None

        question = self.get_object()
        votes = Vote.objects.filter(choice__question=question, user=user)
        if votes.exists():
            return votes.first().choice
        else:
            return None

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['old_choice'] = self.get_old_choice()
        return context


class ResultsView(generic.DetailView):
    """
    View for displaying the results of a question.
    """
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    """
    View for handling user votes on a question.
    """
    question = get_object_or_404(Question, pk=question_id)
    user = request.user
    print("current user is", user.id, "login", user.username)
    print("Real name:", user.first_name, user.last_name)

    if not question.can_vote():
        # User cannot vote on this question, so display an error message.
        messages.error(request, "The poll is not available.")
        return render(request, 'polls/detail.html', {'question': question})

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "You didn't select a choice.")
        return render(request, "polls/detail.html", {'question': question})
    else:
        # check if user already voted.
        is_exist = Vote.objects.filter(choice__question=selected_choice.question,
                                       user=user).exists()
        if is_exist:
            vote = Vote.objects.get(choice__question=selected_choice.question, user=user)
            vote.choice = selected_choice
            vote.save()
            messages.success(request, f"Change vote to {vote.choice.choice_text} has been saved")
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        else:
            # create new vote object.
            vote = Vote(choice=selected_choice, user=user)
            vote.save()
            messages.success(request, f"Your vote for {vote.choice.choice_text} has been saved")
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


@login_required()
def profile(request):
    """
    Showing history of User in profile page.
    """
    user = request.user
    user_votes = Vote.objects.filter(user=user)
    return render(request, 'polls/profile.html', {'user_votes': user_votes})

polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/detail_style.css' %}">

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    {% if message.tags == "error" %}
                        {{ message }}
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <ul class = "choice_button">
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" class="choice_input"
                {% if choice.id == old_choice.id %}
                  checked
                {% endif %}>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            </ul>
        {% endfor %}
    </fieldset>
    <input type="submit" class="vote_button" value="Vote">
</form>
<form action="{% url 'polls:results' question.id %}" method="GET" >
    {% csrf_token %}
    <input type="submit" class="Views" value="Views results" >
</form>

<div class="welcome">
    {% if user.is_authenticated %}
       Welcome back, {{ user.username }}
         <form action="{% url 'logout'%}" method="get">
            {% csrf_token %}
            <input type="submit" class="logout" value="Logout">
        </form>
    {% else %}
        <div class="button-form">
            <form action="{% url 'login' %}" method="get">
                Please <input type="submit" class="login" value="Login">
            </form>
            <form action="{% url 'signup' %}" method="get">
                or <input type="submit" class="signup" value="Sign up">
            </form>
        </div>
    {% endif %}
</div>
<a href="{% url 'polls:index' %}">Go back to list of poll</a>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<h1><b>KU Polls</b></h1>
<h2>Question</h2>
{% if latest_question_list %}
<div id="questionlist" >
    <ul>
    {% for question in latest_question_list %}
    <div class="question">
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            <div class="date">
                Publish date: {{ question.pub_date_str }}
                End date: {{ question.end_date_str }}
            </div>
            <form action="{% url 'polls:results' question.id %}" method="GET" >
                {% csrf_token %}
                <input type="submit" class="Views" value="Results">
            </form>
        </div>
            {% endfor %}
    </ul>
</div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<a class="profile" href="{% url 'polls:profile' %}">Profile</a>
<div class="welcome">
{% if user.is_authenticated %}
   Welcome back, {{ user.username }}
     <form action="{% url 'logout'%}" method="post">
        {% csrf_token %}
        <input type="submit" class="logout" value="Logout">
    </form>
{% else %}
    <div class="button-form">
        <form action="{% url 'login' %}" method="get">
            Please <input type="submit" class="login" value="Login">
        </form>
        <form action="{% url 'signup' %}" method="get">
            or <input type="submit" class="signup" value="Sign up">
        </form>
    </div>
{% endif %}
</div>

polls/templates/polls/profile.html
<h1>Profile</h1>
<div>
    <b>Username: </b> {{ user.username }}
</div>
<h3> Vote History<h3>
<div class="vote_box">
    <table>
        <tr>
            <th>Question</th>
            <th>Choice</th>
            <th></th>
        </tr>
    {% for user_vote in user_votes%}
        <tr>
        <div class="vote_history">
           <td>{{ user_vote.choice.question.question_text}}
            <td>{{user_vote.choice.choice_text}}</td>
            <td>
                <form action= "{% url 'polls:detail' user_vote.choice.question.id %}" method="GET">
                    {% csrf_token %}
                    <input type="submit" class="change_vote" value="Change Vote">
                </form>
            </td>
        </div>
        </tr>
    {% empty %}
    <b>No votes yet</b>
    {% endfor %}
    </table>
</div>
    {% if user.is_authenticated %}
    <form action="{% url 'logout'%}" method="get">
        {% csrf_token %}
        <input type="submit" class="logout" value="Logout">
    </form>
    {% endif %}
<a href="{% url 'polls:index' %}"> Go to index page</a>

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/results_style.css' %}" xmlns="http://www.w3.org/1999/html">
<h1>Result</h1>
<h2>{{ question.question_text }}</h2>


<div class="container">
  {% for choice in question.choice_set.all %}
    {{ choice.choice_text }}
        <div class="vote_bar">
          <div class="bar" style="width: {{choice.votes}}%">{{ choice.votes }}</div>
        </div>
        <div class="votes"> votes </div>
  {% endfor %}
</div>

{% if messages %}
    </div class="success">
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <b class="message">{{ message }}</b>
          {% endif %}
        {% endfor %}
    </div>
{% endif %}

<a href="{% url 'polls:index' %}">Go back to list of poll</a>

<div class="welcome">
{% if user.is_authenticated %}
   Welcome back, {{ user.username }}
     <form action="{% url 'logout'%}" method="get">
        {% csrf_token %}
        <input type="submit" class="logout" value="Logout">
    </form>
{% else %}
    <div class="button-form">
        <form action="{% url 'login' %}" method="get">
            Please <input type="submit" class="login" value="Login">
        </form>
        <form action="{% url 'signup' %}" method="get">
            or <input type="submit" class="signup" value="Sign up">
        </form>
    </div>
{% endif %}
</div>